# Generated by Django 5.2.3 on 2025-07-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
