# Generated by Django 5.2.3 on 2025-08-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, upload_to='skills/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
