# Generated by Django 5.2.3 on 2025-08-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_skill_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='icon',
            new_name='icon_path',
        ),
    ]
