# Generated by Django 5.2.3 on 2025-08-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_icon_skill_icon_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon_path',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.FileField(blank=True, upload_to='skills/'),
        ),
    ]
