# Generated by Django 5.2.3 on 2025-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_skill_icon_path_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.FileField(blank=True, upload_to='static/skills/'),
        ),
    ]
