# Generated by Django 5.2.3 on 2025-08-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
