# Generated by Django 5.2.3 on 2025-08-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_skill_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='order',
        ),
    ]
