# Generated by Django 5.2.3 on 2025-08-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_skill_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='order',
        ),
    ]
