# Generated by Django 5.2.3 on 2025-08-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
